# Generated by Django 2.1.3 on 2018-11-28 16:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models._upload_to_post, verbose_name='Image'),
        ),
    ]
