FROM ikeikeikeike/boot-ads:built-admin as noci
WORKDIR /workspace/boot-ads/admin

ENV DJANGO_SETTINGS_MODULE=ads.settings

COPY ./ ./

RUN cp -Pr /apps/boot-ads/admin/.venv /workspace/boot-ads/admin/ \
  && cp -Pr /apps/boot-ads/admin/ui/node_modules /workspace/boot-ads/admin/ui/

RUN (cd ./ui && npm install -g gulp@3.9.1 typings@2.1.1 webpack@4.25.1 typescript@3.1.6 && npm link gulp) \
          && \
    (cd ./ui && npm install && NODE_ENV=production gulp build) \
          && \
    pip install pipenv && PIPENV_VENV_IN_PROJECT=true pipenv install \
          && \
    (cd ./ads && /workspace/boot-ads/admin/.venv/bin/python manage.py collectstatic --noinput)

# main

FROM ikeikeikeike/docker-python:3.7-slim
WORKDIR /apps/boot-ads/admin

COPY --from=noci /workspace/boot-ads/admin /apps/boot-ads/admin

RUN . /apps/boot-ads/admin/.venv/bin/activate && pip uninstall mysqlclient -y && pip install mysqlclient google
